### ISSUE TITLE
Error at Loading

### ISSUE THREAD

**Issue by Saigara** [vimeo/zendesk-ticket-history#11]
Hi, theres an Error:
https://gyazo.com/d83143ec9c04c61a8a90a7e74d23bf31
Please Help.

* Browser and operating system: Chrome, Safari, Firefox
* App version: 1.0.2
* Description of issue or comments:
* Link to screenshot: https://gyazo.com/d83143ec9c04c61a8a90a7e74d23bf31

**Comment by zenahirsch** [comment]
Unfortunately, I can't debug this with just a screenshot. If this issue is still occurring in the latest version of the app, please open a new ticket and include the contents of your browser's console. Thank you!
