### ISSUE TITLE
Feature: Optional Lightbox

### ISSUE THREAD

**Issue by vipulpradhan** [vimeo/zendesk-ticket-history#12]
Thank you for taking the time to reach out.

* Browser and operating system: Version 69.0.3497.100 (Official Build) (64-bit) and Windows 10 (Version 1803 - Build 17134.345)
* App version: Version 1.0.3
* Description of issue or comments: Is there a way to disable Lightbox preview? So that, once we click a ticket from the list of tickets on the sidebar, it would go straight to that ticket, without showing Lightbox?
* Link to screenshot: NA

**Comment by zenahirsch** [comment]
I am adding a toggle in the app settings to control whether a preview is shown or not. This will go live with the next version. Thanks for the suggestion!
