### ISSUE TITLE
No Longer seeing Closed Tickets

### ISSUE THREAD

**Issue by drcybernut** [vimeo/zendesk-ticket-history#16]
Thank you for taking the time to reach out.

* Browser and operating system:
* App version: 
* Description of issue or comments:
* Link to screenshot:

**Comment by zenahirsch** [comment]
Hi @drcybernut , this is due to a recent app update (at Zendesk's request) that excludes archived tickets the display. This makes the app load faster, but I am still trying to decide if its a worthwhile trade-off. Let me know if you have any particular arguments one way or another.

**Comment by drcybernut** [comment]
Browser and operating system: updated Chrome on Win10x64
App version: 1.0.5
Description of issue or comments: no longer showing closed tickets
![Capture](https://user-images.githubusercontent.com/35745577/65002795-708caa80-d8c3-11e9-9e8b-00c45c759a44.JPG)

My use case of ticket history supports warranty returns for product from business partners to end customers.  It is (was) very convenient not to have to ask if they've participated in the program before and to get the history.  My vote would be to include closed tickets. I am ok with archive tickets (greater than 2 years) being omitted.
