### ISSUE TITLE
Feature Add Request

### ISSUE THREAD

**Issue by johamill** [vimeo/zendesk-ticket-history#3]
Thank you for taking the time to reach out.

* Browser and operating system:
* App version: 1.0.1
* Description of issue or comments: Not an issue but a badly needed feature add for Zendesk (wasn't sure how else to send this to you).  In Zendesk, it's impossible for a support agent to immediately know a customer's satisfaction rating on older tickets or an overall rollup of ticket satisfaction ratings.  This would be a huge add for your app.  If each ticket line in your app also had a little icon with simply a green thumbs up or red thumbs down (or something similar) representing satisfaction ratings on those tickets, the agent starting a new ticket would immediately know historical satisfaction ratings and know if they should proceed with caution, or perhaps to open the previously rated tickets to see why it might have been bad.  Maintaining and increasing CSAT scores is huge for support departments, and immediate customer visibility is something that Zendesk is lacking.  We use another plugin called CoffeeSender, so perhaps seeing a customer with bad satisfaction ratings would tell the agent to send them a coffee to help cheer them up.  Is this something you could add with relative ease at this point?  As I mentioned, this would be huge for our organization, and I know it would be for others as well.  Thanks for your time!
* Link to screenshot:

**Comment by zenahirsch** [comment]
This is implemented and can be enabled in the app settings.
