### ISSUE TITLE
App breaks on tickets with null value subject lines

### ISSUE THREAD

**Issue by Bmosko9** [vimeo/zendesk-ticket-history#4]
The app becomes stuck in a loading loop when tickets fail to have a subject line. In Zendesk, you can disable the subject line by making it non-editable online.  See image of settings page below and note that `editable` is unchecked. 
![image](https://user-images.githubusercontent.com/25111133/35524928-ea96339e-04d7-11e8-8afb-ee6aa8555a5f.png)

This causes a logic error in the Ticket History app, where the app tries to evaluate the length of the null value. 
![image](https://user-images.githubusercontent.com/25111133/35524762-6790b71c-04d7-11e8-9693-20789438052e.png)

**Comment by zenahirsch** [comment]
Thanks for the report! This will be fixed in the next version published to the marketplace.

**Comment by Bmosko9** [comment]
Woohoo!
