### ISSUE TITLE
Ticket history won't load in ZenDesk

### ISSUE THREAD

**Issue by sebdsti** [vimeo/zendesk-ticket-history#5]
Hi there,

Plugin installs fine, appears on the right hand-side on a ticket view, but the ticket history itself doesn't load, stuck on progress bar (three green dots).
Tried with and without content blocker

Thank you!

Logs from Safari without content-blocker:
[Error] Resource blocked by content blocker
	o (cai.min.js:1:233952)
	enqueue (cai.min.js:1:186079)
	onpage (cai.min.js:1:184394)
	(anonymous function) (cai.min.js:1:183776)
	emit (cai.min.js:1:247814)
	(anonymous function) (cai.min.js:1:244319)
	_invoke (cai.min.js:1:53765)
	(anonymous function) (cai.min.js:1:244319)
	page (cai.min.js:1:52676)
	(anonymous function) (cai.min.js:1:244319)
	(anonymous function) (cai.min.js:1:318541)
	onload (cai.min.js:1:318590)
[Error] XMLHttpRequest cannot load https://api.segment.io/v1/p due to access control checks.
	o (cai.min.js:1:233952)
	enqueue (cai.min.js:1:186079)
	onpage (cai.min.js:1:184394)
	(anonymous function) (cai.min.js:1:183776)
	emit (cai.min.js:1:247814)
	(anonymous function) (cai.min.js:1:244319)
	_invoke (cai.min.js:1:53765)
	(anonymous function) (cai.min.js:1:244319)
	page (cai.min.js:1:52676)
	(anonymous function) (cai.min.js:1:244319)
	(anonymous function) (cai.min.js:1:318541)
	onload (cai.min.js:1:318590)
[Error] Resource blocked by content blocker
	o (cai.min.js:1:233952)
	enqueue (cai.min.js:1:186079)
	ontrack (cai.min.js:1:184611)
	(anonymous function) (cai.min.js:1:183776)
	emit (cai.min.js:1:247814)
	(anonymous function) (cai.min.js:1:244319)
	_invoke (cai.min.js:1:53765)
	(anonymous function) (cai.min.js:1:244319)
	track (cai.min.js:1:51163)
	(anonymous function) (cai.min.js:1:244319)
	(anonymous function) (cai.min.js:1:318541)
	onload (cai.min.js:1:318590)
[Error] XMLHttpRequest cannot load https://api.segment.io/v1/t due to access control checks.
	o (cai.min.js:1:233952)
	enqueue (cai.min.js:1:186079)
	ontrack (cai.min.js:1:184611)
	(anonymous function) (cai.min.js:1:183776)
	emit (cai.min.js:1:247814)
	(anonymous function) (cai.min.js:1:244319)
	_invoke (cai.min.js:1:53765)
	(anonymous function) (cai.min.js:1:244319)
	track (cai.min.js:1:51163)
	(anonymous function) (cai.min.js:1:244319)
	(anonymous function) (cai.min.js:1:318541)
	onload (cai.min.js:1:318590)
[Error] Resource blocked by content blocker
	o (cai.min.js:1:233952)
	enqueue (cai.min.js:1:186079)
	onidentify (cai.min.js:1:184458)
	(anonymous function) (cai.min.js:1:183776)
	emit (cai.min.js:1:247814)
	(anonymous function) (cai.min.js:1:244319)
	_invoke (cai.min.js:1:53765)
	(anonymous function) (cai.min.js:1:244319)
	identify (cai.min.js:1:50238)
	(anonymous function) (cai.min.js:1:244319)
	(anonymous function) (cai.min.js:1:318541)
	onload (cai.min.js:1:318590)
[Error] XMLHttpRequest cannot load https://api.segment.io/v1/i due to access control checks.
	o (cai.min.js:1:233952)
	enqueue (cai.min.js:1:186079)
	onidentify (cai.min.js:1:184458)
	(anonymous function) (cai.min.js:1:183776)
	emit (cai.min.js:1:247814)
	(anonymous function) (cai.min.js:1:244319)
	_invoke (cai.min.js:1:53765)
	(anonymous function) (cai.min.js:1:244319)
	identify (cai.min.js:1:50238)
	(anonymous function) (cai.min.js:1:244319)
	(anonymous function) (cai.min.js:1:318541)
	onload (cai.min.js:1:318590)
[Error] Resource blocked by content blocker
	o (cai.min.js:1:233952)
	enqueue (cai.min.js:1:186079)
	ongroup (cai.min.js:1:184519)
	(anonymous function) (cai.min.js:1:183776)
	emit (cai.min.js:1:247814)
	(anonymous function) (cai.min.js:1:244319)
	_invoke (cai.min.js:1:53765)
	(anonymous function) (cai.min.js:1:244319)
	group (cai.min.js:1:50667)
	(anonymous function) (cai.min.js:1:244319)
	(anonymous function) (cai.min.js:1:318541)
	onload (cai.min.js:1:318590)
[Error] XMLHttpRequest cannot load https://api.segment.io/v1/g due to access control checks.
	o (cai.min.js:1:233952)
	enqueue (cai.min.js:1:186079)
	ongroup (cai.min.js:1:184519)
	(anonymous function) (cai.min.js:1:183776)
	emit (cai.min.js:1:247814)
	(anonymous function) (cai.min.js:1:244319)
	_invoke (cai.min.js:1:53765)
	(anonymous function) (cai.min.js:1:244319)
	group (cai.min.js:1:50667)
	(anonymous function) (cai.min.js:1:244319)
	(anonymous function) (cai.min.js:1:318541)
	onload (cai.min.js:1:318590)
[Error] Unhandled Promise Rejection: TypeError: null is not an object (evaluating 'ticket.subject.length')
	_loop (ticket_sidebar.js:156)
	formatTickets (ticket_sidebar.js:181)
	renderMain (ticket_sidebar.js:102)
	(anonymous function) (ticket_sidebar.js:52)
	promiseReactionJob

Logs from Safari with content-blocker active:

[Error] Resource blocked by content blocker
	o (cai.min.js:1:233952)
	enqueue (cai.min.js:1:186079)
	onpage (cai.min.js:1:184394)
	(anonymous function) (cai.min.js:1:183776)
	emit (cai.min.js:1:247814)
	(anonymous function) (cai.min.js:1:244319)
	_invoke (cai.min.js:1:53765)
	(anonymous function) (cai.min.js:1:244319)
	page (cai.min.js:1:52676)
	(anonymous function) (cai.min.js:1:244319)
	(anonymous function) (cai.min.js:1:318541)
	onload (cai.min.js:1:318590)
[Error] XMLHttpRequest cannot load https://api.segment.io/v1/p due to access control checks.
	o (cai.min.js:1:233952)
	enqueue (cai.min.js:1:186079)
	onpage (cai.min.js:1:184394)
	(anonymous function) (cai.min.js:1:183776)
	emit (cai.min.js:1:247814)
	(anonymous function) (cai.min.js:1:244319)
	_invoke (cai.min.js:1:53765)
	(anonymous function) (cai.min.js:1:244319)
	page (cai.min.js:1:52676)
	(anonymous function) (cai.min.js:1:244319)
	(anonymous function) (cai.min.js:1:318541)
	onload (cai.min.js:1:318590)
[Error] Resource blocked by content blocker
	o (cai.min.js:1:233952)
	enqueue (cai.min.js:1:186079)
	ontrack (cai.min.js:1:184611)
	(anonymous function) (cai.min.js:1:183776)
	emit (cai.min.js:1:247814)
	(anonymous function) (cai.min.js:1:244319)
	_invoke (cai.min.js:1:53765)
	(anonymous function) (cai.min.js:1:244319)
	track (cai.min.js:1:51163)
	(anonymous function) (cai.min.js:1:244319)
	(anonymous function) (cai.min.js:1:318541)
	onload (cai.min.js:1:318590)
[Error] XMLHttpRequest cannot load https://api.segment.io/v1/t due to access control checks.
	o (cai.min.js:1:233952)
	enqueue (cai.min.js:1:186079)
	ontrack (cai.min.js:1:184611)
	(anonymous function) (cai.min.js:1:183776)
	emit (cai.min.js:1:247814)
	(anonymous function) (cai.min.js:1:244319)
	_invoke (cai.min.js:1:53765)
	(anonymous function) (cai.min.js:1:244319)
	track (cai.min.js:1:51163)
	(anonymous function) (cai.min.js:1:244319)
	(anonymous function) (cai.min.js:1:318541)
	onload (cai.min.js:1:318590)
[Error] Resource blocked by content blocker
	o (cai.min.js:1:233952)
	enqueue (cai.min.js:1:186079)
	onidentify (cai.min.js:1:184458)
	(anonymous function) (cai.min.js:1:183776)
	emit (cai.min.js:1:247814)
	(anonymous function) (cai.min.js:1:244319)
	_invoke (cai.min.js:1:53765)
	(anonymous function) (cai.min.js:1:244319)
	identify (cai.min.js:1:50238)
	(anonymous function) (cai.min.js:1:244319)
	(anonymous function) (cai.min.js:1:318541)
	onload (cai.min.js:1:318590)
[Error] XMLHttpRequest cannot load https://api.segment.io/v1/i due to access control checks.
	o (cai.min.js:1:233952)
	enqueue (cai.min.js:1:186079)
	onidentify (cai.min.js:1:184458)
	(anonymous function) (cai.min.js:1:183776)
	emit (cai.min.js:1:247814)
	(anonymous function) (cai.min.js:1:244319)
	_invoke (cai.min.js:1:53765)
	(anonymous function) (cai.min.js:1:244319)
	identify (cai.min.js:1:50238)
	(anonymous function) (cai.min.js:1:244319)
	(anonymous function) (cai.min.js:1:318541)
	onload (cai.min.js:1:318590)
[Error] Resource blocked by content blocker
	o (cai.min.js:1:233952)
	enqueue (cai.min.js:1:186079)
	ongroup (cai.min.js:1:184519)
	(anonymous function) (cai.min.js:1:183776)
	emit (cai.min.js:1:247814)
	(anonymous function) (cai.min.js:1:244319)
	_invoke (cai.min.js:1:53765)
	(anonymous function) (cai.min.js:1:244319)
	group (cai.min.js:1:50667)
	(anonymous function) (cai.min.js:1:244319)
	(anonymous function) (cai.min.js:1:318541)
	onload (cai.min.js:1:318590)
[Error] XMLHttpRequest cannot load https://api.segment.io/v1/g due to access control checks.
	o (cai.min.js:1:233952)
	enqueue (cai.min.js:1:186079)
	ongroup (cai.min.js:1:184519)
	(anonymous function) (cai.min.js:1:183776)
	emit (cai.min.js:1:247814)
	(anonymous function) (cai.min.js:1:244319)
	_invoke (cai.min.js:1:53765)
	(anonymous function) (cai.min.js:1:244319)
	group (cai.min.js:1:50667)
	(anonymous function) (cai.min.js:1:244319)
	(anonymous function) (cai.min.js:1:318541)
	onload (cai.min.js:1:318590)
[Error] Unhandled Promise Rejection: TypeError: null is not an object (evaluating 'ticket.subject.length')
	_loop (ticket_sidebar.js:156)
	formatTickets (ticket_sidebar.js:181)
	renderMain (ticket_sidebar.js:102)
	(anonymous function) (ticket_sidebar.js:52)
	promiseReactionJob

**Comment by zenahirsch** [comment]
This should be fixed. Please let me know if the issue persists.
