### ISSUE TITLE
"Uh oh, looks like there was an error" - Error today

### ISSUE THREAD

**Issue by dung4993** [vimeo/zendesk-ticket-history#6]
Thank you for taking the time to reach out.

* Browser and operating system: Chrome Version 69.0.3497.100 | Mac OS 0.13.6
* App version: Version 1.0.2
* Description of issue or comments: The app is not working on Zendesk anymore today. It showed the error as not connecting. 
* Link to screenshot: http://prntscr.com/l2c74c

**Comment by zenahirsch** [comment]
Thanks for getting in touch. The fix has been submitted and should be available once Zendesk has approved it. I apologize for the inconvenience.
