### ISSUE TITLE
Uh oh errors in the app

### ISSUE THREAD

**Issue by gtimpane** [vimeo/zendesk-ticket-history#7]
* Browser and operating system: Chrome, Mac OS
* App version: Version 1.0.2 - Last updated 3 hours ago
* Description of issue or comments: The app isn't loading any ticket history and provides the message, 

> Uh oh, looks like there was an error. Please report this, along with your browser's console contents, by opening a ticket.

The console reads the following error:

> Unsafe JavaScript attempt to initiate navigation for frame with origin 'https://subdomain.zendesk.com' from frame with URL 'https://116762.apps.zdusercontent.com/116762/assets/1537802865-a04732dd700e3eea6b48779a2ab77611/index.html?origin=https%3A%2F%2Fsubdomain.zendesk.com&app_guid=e9d40931-8b4a-4f81-afb3-179549979242'. The frame attempting navigation of the top-level window is sandboxed, but the flag of 'allow-top-navigation' or 'allow-top-navigation-by-user-activation' is not set. 

Also seeing:

> ticket_sidebar.js:123 TypeError: Cannot read property 'score' of null
    at _loop (ticket_sidebar.js:169)
    at eval (ticket_sidebar.js:216)
    at new Promise (<anonymous>)
    at TicketSidebar.formatTickets (ticket_sidebar.js:147)
    at TicketSidebar.renderMain (ticket_sidebar.js:107)
    at eval (ticket_sidebar.js:51)
(anonymous) @ ticket_sidebar.js:123
Promise.catch (async)
renderMain @ ticket_sidebar.js:122
(anonymous) @ ticket_sidebar.js:51
Promise.then (async)
(anonymous) @ ticket_sidebar.js:50
Promise.then (async)
TicketSidebar @ ticket_sidebar.js:47
(anonymous) @ index.js:21
Promise.then (async)
(anonymous) @ index.js:16
(anonymous) @ zaf_sdk.js:311
triggerEvent @ zaf_sdk.js:310
messageHandler @ zaf_sdk.js:384

* Link to screenshot: ![ticket history errors](https://user-images.githubusercontent.com/25339717/46513439-a9985000-c815-11e8-8a68-5b0d01330968.png)

**Comment by zenahirsch** [comment]
Thanks for getting in touch. The fix has been submitted and should be available once Zendesk has approved it. I apologize for the inconvenience.
