### ISSUE TITLE
Ticket History / Zendesk

### ISSUE THREAD

**Issue by fabrice-naturalforme** [vimeo/zendesk-ticket-history#8]
Thank you for taking the time to reach out.

* Browser and operating system: Chrome
* App version:  
* Description of issue or comments: "Uh oh, looks like there was an error. Please report this, along with your browser's console contents, by opening a ticket."
* Link to screenshot:
![image](https://user-images.githubusercontent.com/43876138/46524429-20bafc00-c889-11e8-8057-3e7a3d634242.png)

**Comment by zenahirsch** [comment]
Thanks for getting in touch. The fix has been submitted and should be available once Zendesk has approved it. I apologize for the inconvenience.

**Comment by fabrice-naturalforme** [comment]
Thank you !
