### ISSUE TITLE
Ticket History Error 

### ISSUE THREAD

**Issue by mintyfresh89** [vimeo/zendesk-ticket-history#9]
**Browser and operating system:** Google Chrome/IE10 -- Windows10

**App version:** Version 1.0.2 - Last updated 11 hours ago 

**Description of issue or comments:** The app isn't loading any ticket history and provides the message

_Uh oh, looks like there was an error. Please report this, along with your browser's console contents, by opening a ticket._

The console reads the following error:

TypeError: Cannot read property 'score' of null
    at _loop (ticket_sidebar.js:169)
    at eval (ticket_sidebar.js:216)
    at new Promise (<anonymous>)
    at TicketSidebar.formatTickets (ticket_sidebar.js:147)
    at TicketSidebar.renderMain (ticket_sidebar.js:107)
    at eval (ticket_sidebar.js:51)
(anonymous) @ ticket_sidebar.js:123
ticket_sidebar.js:123 TypeError: Cannot read property 'score' of null
    at _loop (ticket_sidebar.js:169)
    at eval (ticket_sidebar.js:216)
    at new Promise (<anonymous>)
    at TicketSidebar.formatTickets (ticket_sidebar.js:147)
    at TicketSidebar.renderMain (ticket_sidebar.js:107)
    at eval (ticket_sidebar.js:51)
(anonymous) @ ticket_sidebar.js:123
Unsafe JavaScript attempt to initiate navigation for frame with origin 'https://subdomain.zendesk.com' from frame with URL 'https://116762.apps.zdusercontent.com/116762/assets/1537802865-a04732dd700e3eea6b48779a2ab77611/index.html?origin=https%3A%2F%2Fhelp-subdomain.zendesk.com&app_guid=a21bb4db-f5e2-425a-9f35-70b0fd2df75b'. The frame attempting navigation of the top-level window is sandboxed, but the flag of 'allow-top-navigation' or 'allow-top-navigation-by-user-activation' is not set.

Unsafe JavaScript attempt to initiate navigation for frame with origin 'https://help-subdomain.zendesk.com' from frame with URL 'https://116762.apps.zdusercontent.com/116762/assets/1537802865-a04732dd700e3eea6b48779a2ab77611/index.html?origin=https%3A%2F%2Fhelp-subdomain.zendesk.com&app_guid=a21bb4db-f5e2-425a-9f35-70b0fd2df75b'. The frame attempting navigation of the top-level window is sandboxed, but the flag of 'allow-top-navigation' or 'allow-top-navigation-by-user-activation' is not set.

Unsafe JavaScript attempt to initiate navigation for frame with origin 'https://help-subdomain.zendesk.com' from frame with URL 'https://116762.apps.zdusercontent.com/116762/assets/1537802865-a04732dd700e3eea6b48779a2ab77611/index.html?origin=https%3A%2F%2Fhelp-subdomain.zendesk.com&app_guid=a21bb4db-f5e2-425a-9f35-70b0fd2df75b'. The frame attempting navigation of the top-level window is sandboxed, but the flag of 'allow-top-navigation' or 'allow-top-navigation-by-user-activation' is not set.

Unsafe JavaScript attempt to initiate navigation for frame with origin 'https://help-subdomain.zendesk.com' from frame with URL 'https://116762.apps.zdusercontent.com/116762/assets/1537802865-a04732dd700e3eea6b48779a2ab77611/index.html?origin=https%3A%2F%2Fhelp-subdomain.zendesk.com&app_guid=a21bb4db-f5e2-425a-9f35-70b0fd2df75b'. The frame attempting navigation of the top-level window is sandboxed, but the flag of 'allow-top-navigation' or 'allow-top-navigation-by-user-activation' is not set.

Unsafe JavaScript attempt to initiate navigation for frame with origin 'https://help-subdomain.zendesk.com' from frame with URL 'https://116762.apps.zdusercontent.com/116762/assets/1537802865-a04732dd700e3eea6b48779a2ab77611/index.html?origin=https%3A%2F%2Fhelp-subdomain.zendesk.com&app_guid=a21bb4db-f5e2-425a-9f35-70b0fd2df75b'. The frame attempting navigation of the top-level window is sandboxed, but the flag of 'allow-top-navigation' or 'allow-top-navigation-by-user-activation' is not set.

Unsafe JavaScript attempt to initiate navigation for frame with origin 'https://help-subdomain.zendesk.com' from frame with URL 'https://116762.apps.zdusercontent.com/116762/assets/1537802865-a04732dd700e3eea6b48779a2ab77611/index.html?origin=https%3A%2F%2Fhelp-subdomain.zendesk.com&app_guid=a21bb4db-f5e2-425a-9f35-70b0fd2df75b'. The frame attempting navigation of the top-level window is sandboxed, but the flag of 'allow-top-navigation' or 'allow-top-navigation-by-user-activation' is not set.

Also seeing:

ticket_sidebar.js:123_ TypeError: Cannot read property 'score' of null
at _loop (ticket_sidebar.js:169)
at eval (ticket_sidebar.js:216)
at new Promise ()
at TicketSidebar.formatTickets (ticket_sidebar.js:147)
at TicketSidebar.renderMain (ticket_sidebar.js:107)
at eval (ticket_sidebar.js:51)
(anonymous) @ ticket_sidebar.js:123
Promise.catch (async)
renderMain @ ticket_sidebar.js:122
(anonymous) @ ticket_sidebar.js:51
Promise.then (async)
(anonymous) @ ticket_sidebar.js:50
Promise.then (async)
TicketSidebar @ ticket_sidebar.js:47
(anonymous) @ index.js:21
Promise.then (async)
(anonymous) @ index.js:16
(anonymous) @ zaf_sdk.js:311
triggerEvent @ zaf_sdk.js:310
messageHandler @ zaf_sdk.js:384

**Link to screenshot:** 
![screenshot-ticket-history](https://user-images.githubusercontent.com/43879111/46530557-19214480-c8d5-11e8-800d-ba05503d3d9d.png)

**Comment by zenahirsch** [comment]
Thanks for getting in touch. The fix has been submitted and should be available once Zendesk has approved it. I apologize for the inconvenience.
